drop name: 'Beatrice Tohni'
drop mail: 'beatrice.tohni@oracle.com'
drop guid: 'btohni'
new dire: 'mkdir '
goto talon: 'cd ~/.talon/user/knausj_talon'
ops: ' = '
const: 'const'
commit: 'gc -am \''
console log: 'console.log(\''
edit talon: 'vim .talon/user/knausj_talon/alias.talon'
mine this: 'mine .'
code this: 'code .'
root: 'cd ~/ada'
alien: 'asyncio'
tick: '`'
